# Generated by Django 4.2.13 on 2024-06-26 10:29

import pytz
from django.db import migrations


def forwards(apps, schema_editor):
    timezone_obj = apps.get_model("user", "Timezone")
    for timezone in pytz.all_timezones:
        timezone_obj(name=timezone).save()

def backwords(apps, schema_editor):
    timezone_obj = apps.get_model("user", "Timezone")
    timezone_obj.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=backwords)
    ]
