# Generated by Django 4.2.13 on 2024-07-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_add_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techstack',
            name='rating',
        ),
        migrations.AddField(
            model_name='techstack',
            name='proficiency_level',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Basic', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='grade',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
