# Generated by Django 4.2.13 on 2024-07-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_techstack_rating_techstack_proficiency_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techstack',
            name='proficiency_level',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Basic', max_length=20),
        ),
    ]
