# Generated by Django 4.2.13 on 2024-07-25 09:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_date_certification_issued_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'], message='Only PDF, DOC, or DOCX files are allowed for the resume.')], verbose_name='Resume')),
                ('onepage_resume', models.FileField(upload_to='onepage_resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ppt', 'pptx'], message='Only PPT or PPTX files are allowed for the one-page resume.')], verbose_name='One-page Resume')),
                ('others', models.FileField(upload_to='other_documents')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='user.userprofile')),
            ],
            options={
                'verbose_name_plural': 'Documents',
            },
        ),
    ]
