# Generated by Django 4.2.13 on 2024-07-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='others',
            field=models.FileField(blank=True, null=True, upload_to='other_documents'),
        ),
    ]
