# Generated by Django 4.2.13 on 2024-07-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_education_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documents',
            options={},
        ),
        migrations.RemoveField(
            model_name='documents',
            name='onepage_resume',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='others',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='resume',
        ),
        migrations.AddField(
            model_name='documents',
            name='document_type',
            field=models.CharField(choices=[('resume', 'Resume'), ('onepage_resume', 'One-page Resume'), ('others', 'Others')], default=1, max_length=20, verbose_name='Document Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documents',
            name='file',
            field=models.FileField(default=1, upload_to='documents/', verbose_name='File'),
            preserve_default=False,
        ),
    ]
