# Generated by Django 4.2.13 on 2024-07-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_documents_document_type_alter_documents_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='document_type',
            field=models.CharField(choices=[('resume', 'Resume'), ('onepage_resume', 'One Page Resume'), ('others', 'Others')], max_length=50),
        ),
    ]
