# Generated by Django 4.2.13 on 2024-08-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_documents_document_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timezone',
            old_name='name',
            new_name='label',
        ),
        migrations.AddField(
            model_name='timezone',
            name='value',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
